### ISSUE TITLE
关于树莓派Arch脚本不可以用问题

### ISSUE THREAD

**Issue by ghost** [Hysian/QzoneVote#1]
作者你好，希望你可以帮我解决一下：
我是Arch arm系统.安装了python2.7和python3.6两个版本.
在2.7下，运行python2 vote.py
报错，然后安装了pip2 install cookies发现还是错误
[root@alarm QzoneVote]# python2 vote.py
Traceback (most recent call last):
  File "vote.py", line 11, in <module>
    from cookies import cookies
ImportError: cannot import name cookies
在3.6下测试也是报错
[root@alarm QzoneVote]# python vote.py
  File "vote.py", line 31
    print msg
            ^
SyntaxError: Missing parentheses in call to 'print'

请问作者需要修改什么，或者说是缺什么库吗？请告之.谢谢
最后有个想法，不知道可以添加一个 自动回复点赞的说说吗，把word里面的内容回复上去。希望可以用你的宝贵时间，添加一下这个功能，

**Comment by ShaoZeMing** [comment]
语法错误，print后加()   例：print(msg)

**Comment by yixian-huang** [comment]
不好意思，很久沒有维护这个项目了，我这个是基于python2.7的，所以就像楼上说的那样，要修改语法。你所说的新功能我可以最近去添加一下
